-- MySQL Script generated by MySQL Workbench
-- 05/22/16 18:47:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema e_comm_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema e_comm_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e_comm_db` DEFAULT CHARACTER SET utf8 ;
USE `e_comm_db` ;

-- -----------------------------------------------------
-- Table `e_comm_db`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_comm_db`.`USER` ;

CREATE TABLE IF NOT EXISTS `e_comm_db`.`USER` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(105) NULL,
  `address` VARCHAR(45) NULL,
  `login` VARCHAR(100) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_comm_db`.`CITY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_comm_db`.`CITY` ;

CREATE TABLE IF NOT EXISTS `e_comm_db`.`CITY` (
  `cityID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(105) NULL,
  `apt` INT NULL,
  `country` VARCHAR(105) NULL,
  PRIMARY KEY (`cityID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_comm_db`.`COSTUMER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_comm_db`.`COSTUMER` ;

CREATE TABLE IF NOT EXISTS `e_comm_db`.`COSTUMER` (
  `costumerID` INT NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(45) NULL,
  `date_created` DATETIME NULL,
  `type_auth` INT NULL,
  `status` INT NULL,
  `id_user` INT NOT NULL,
  `id_city` INT NOT NULL,
  PRIMARY KEY (`costumerID`, `id_user`, `id_city`),
  INDEX `fk_COSTUMER_USER1_idx` (`id_user` ASC),
  INDEX `fk_COSTUMER_CITY1_idx` (`id_city` ASC),
  CONSTRAINT `fk_COSTUMER_USER1`
    FOREIGN KEY (`id_user`)
    REFERENCES `e_comm_db`.`USER` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COSTUMER_CITY1`
    FOREIGN KEY (`id_city`)
    REFERENCES `e_comm_db`.`CITY` (`cityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_comm_db`.`POSITION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_comm_db`.`POSITION` ;

CREATE TABLE IF NOT EXISTS `e_comm_db`.`POSITION` (
  `positionID` INT NOT NULL AUTO_INCREMENT,
  `lat` DOUBLE NULL,
  `lang` DOUBLE NULL,
  `address` VARCHAR(200) NULL,
  PRIMARY KEY (`positionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_comm_db`.`STORE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_comm_db`.`STORE` ;

CREATE TABLE IF NOT EXISTS `e_comm_db`.`STORE` (
  `storeID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `Store_url` VARCHAR(150) NULL,
  `Status` INT NULL,
  `STOREcol` VARCHAR(45) NULL,
  `id_position` INT NOT NULL,
  `id_costumer` INT NOT NULL,
  PRIMARY KEY (`storeID`, `id_position`),
  INDEX `fk_STORE_POSITION1_idx` (`id_position` ASC),
  INDEX `fk_STORE_COSTUMER1_idx` (`id_costumer` ASC),
  CONSTRAINT `fk_STORE_POSITION1`
    FOREIGN KEY (`id_position`)
    REFERENCES `e_comm_db`.`POSITION` (`positionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STORE_COSTUMER1`
    FOREIGN KEY (`id_costumer`)
    REFERENCES `e_comm_db`.`COSTUMER` (`costumerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_comm_db`.`CATEGORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_comm_db`.`CATEGORY` ;

CREATE TABLE IF NOT EXISTS `e_comm_db`.`CATEGORY` (
  `categoryID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `Sub_Cat` VARCHAR(45) NULL,
  `Description` MEDIUMTEXT NULL,
  PRIMARY KEY (`categoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_comm_db`.`IMAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_comm_db`.`IMAGE` ;

CREATE TABLE IF NOT EXISTS `e_comm_db`.`IMAGE` (
  `imageID` INT NOT NULL AUTO_INCREMENT,
  `url_image` VARCHAR(100) NULL,
  `ext` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `IMAGEcol` VARCHAR(45) NULL,
  PRIMARY KEY (`imageID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_comm_db`.`PRODUCT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_comm_db`.`PRODUCT` ;

CREATE TABLE IF NOT EXISTS `e_comm_db`.`PRODUCT` (
  `productID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `description` MEDIUMTEXT NULL,
  `date_created` DATE NULL,
  `price` DOUBLE NULL,
  `status` INT NULL,
  `quantity` INT NULL,
  `id_category` INT NOT NULL,
  `id_image` INT NOT NULL,
  `id_store` INT NOT NULL,
  PRIMARY KEY (`productID`, `id_category`, `id_image`, `id_store`),
  INDEX `fk_PRODUCT_CATEGORY_idx` (`id_category` ASC),
  INDEX `fk_PRODUCT_IMAGE1_idx` (`id_image` ASC),
  INDEX `fk_PRODUCT_STORE1_idx` (`id_store` ASC),
  CONSTRAINT `fk_PRODUCT_CATEGORY`
    FOREIGN KEY (`id_category`)
    REFERENCES `e_comm_db`.`CATEGORY` (`categoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCT_IMAGE1`
    FOREIGN KEY (`id_image`)
    REFERENCES `e_comm_db`.`IMAGE` (`imageID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCT_STORE1`
    FOREIGN KEY (`id_store`)
    REFERENCES `e_comm_db`.`STORE` (`storeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_comm_db`.`ORDER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `e_comm_db`.`ORDER` ;

CREATE TABLE IF NOT EXISTS `e_comm_db`.`ORDER` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `DateCreated` DATETIME NULL,
  `DateCloture` DATETIME NULL,
  `status` INT NULL,
  `orderQte` INT NULL,
  `id_costumer` INT NOT NULL,
  `id_product` INT NOT NULL,
  PRIMARY KEY (`orderID`, `id_costumer`, `id_product`),
  INDEX `fk_ORDER_COSTUMER1_idx` (`id_costumer` ASC),
  INDEX `fk_ORDER_PRODUCT1_idx` (`id_product` ASC),
  CONSTRAINT `fk_ORDER_COSTUMER1`
    FOREIGN KEY (`id_costumer`)
    REFERENCES `e_comm_db`.`COSTUMER` (`costumerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDER_PRODUCT1`
    FOREIGN KEY (`id_product`)
    REFERENCES `e_comm_db`.`PRODUCT` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
